apiVersion: v2
name: sd-currency-exchange
description: "BIAN Service Domain: Currency Exchange (Process pattern, Operations and Execution)"
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - bian
  - process
annotations:
  bian/business-area: "Operations and Execution"
  bian/business-domain: "Operations"
  bian/asset-type: "FX Deal"
  bian/control-record: "FX Deal Procedure"
